django_tutorial/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [

    # Without using generic views:
    # /polls/
    # path('', views.index, name='index'),
    # #/polls/1/
    # path('<int:question_id>/', views.detail, name='detail'),
    # #/polls/1/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # #/polls/1/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),

    # With generic views:
    # /polls/
    path('', views.IndexView.as_view(), name='index'),
    #/polls/1/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #/polls/1/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #/polls/1/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    #/polls/1/delete/
    path('<int:pk>/delete/', views.QuestionDelete.as_view(), name='delete'),
    path('create/', views.QuestionCreate.as_view(), name='create'),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import NumberInput

from .models import Question

class QuestionForm(ModelForm):

    choice1 = forms.CharField(max_length=100, required=False, label="Choice 1", widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice2 = forms.CharField(max_length=100, required=False, label="Choice 2", widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice3 = forms.CharField(max_length=100, required=False, label="Choice 3", widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice4 = forms.CharField(max_length=100, required=False, label="Choice 4", widget=forms.TextInput(attrs={'class': 'form-control'}))

    pub_date = forms.DateField(widget=NumberInput(attrs={'type': 'date', 'class': 'form-control'}), label="Date")
    question_text = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}), label="Question")

    class Meta:
        model = Question
        fields = [
            'question_text',
            'pub_date',
        ]

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import DeleteView, CreateView
from .models import Question, Choice
from .forms import QuestionForm

# Without using generic views

# def index(request):
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    context = {'latest_question_list':latest_question_list}
#    return render(request, 'polls/index.html', context)

# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#         context = {'question':question}
#     except Question.DoesNotExist:
#         raise Http404("Question Does Not Exist!")
#     return render(request, 'polls/detail.html', context)

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question':question})


#Using generic Views
class IndexView(generic.ListView):
    form = QuestionForm
    template_name='polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

class QuestionDelete(DeleteView):
    model = Question
    template_name = 'polls/confirm_delete.html'
    success_url = reverse_lazy('polls:index')

    def get_context_data(self, **kwargs):
        context = super(QuestionDelete, self).get_context_data(**kwargs)
        id = self.kwargs.get('pk')
        votes = Choice.objects.filter(question_id=id).values('votes')
        totalVotes = 0
        for vote in votes:
            totalVotes += vote['votes']
        context['total_votes'] = totalVotes
        return context

class QuestionCreate(CreateView):
    model = Question
    form_class = QuestionForm
    template_name = 'polls/add_question.html'
    success_url = reverse_lazy('polls:index')

    def filter_choices(self, form):
        choices =  {
            'choice1': form.cleaned_data['choice1'],
            'choice2': form.cleaned_data['choice2'],
            'choice3': form.cleaned_data['choice3'],
            'choice4': form.cleaned_data['choice4']
        }
        return  {key: value for key, value in choices.items() if value != ""}
        
    def form_valid(self, form):
        if form.is_valid:
            question = form.save()
            for choice in self.filter_choices(form).values():
               Choice(question=question, choice_text=choice).save()
        return super().form_valid(form)
        

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "No Choice Selected!",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

polls/templates/polls/add_question.html
{% extends 'polls/base.html' %}

{% block content %}

<div class="container">
    <form method="post">
        <div class="form-group text-center">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Save">
        </div>
    </form>
</div>

{% endblock content %}

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Polls</title>
</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="nav-link" href="{% url 'polls:index' %}">Home</a>
    </nav>
</header>

<body>
    {% block content %}

    {% endblock content %}
</body>

</html>

polls/templates/polls/confirm_delete.html
{% extends 'polls/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <div class="p-3 mb-2 bg-warning text-dark">
        <p class="font-weight-bold">Are you sure you want to delete "{{ object }}"?</p>
        <p class="font-weight-bold">{{ total_votes }} vote{{ total_votes|pluralize }} will also be deleted!</p>
        <input class="btn btn-danger" type="submit" value="Confirm">
        <button onclick="window.history.back();" class="btn btn-info" type="button">Cancel</button>
    </div>
</form>

{% endblock content %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}

<div class='container'>
    <p class='text-center display-4'>{{ question.question_text }}
    <p>
        {% if error_message %}
    <p class="p-3 mb-2 bg-danger text-white"><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <table class="table">
            <tr>
                <th scope="row">
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                </th>
            </tr>
        </table>
        {% endfor %}
        <input class="btn btn-success" type="submit" value="Vote?">
    </form>
</div>

{% endblock content %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}

{% if latest_question_list %}
<div class="container">
    <br>
    {% for question in latest_question_list %}
    <div class="row">
        <div class="col-8">
            <a class="badge badge-info" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        </div>
        <div class="col-4">
            <a class="btn btn-danger btn-sm" href="{% url 'polls:delete' question.id %}">Delete</a>
        </div>
    </div>
    <br>
    {% endfor %}
    {% else %}
    <p class="p-3 mb-2 bg-warning text-dark">No polls are available.</p>
    {% endif %}
    <br>
    <a class="btn btn-primary" href="{% url 'polls:create' %}">Add Question</a>
</div>


{% endblock content %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}

<div class="container">
    <h1 class='text-center display-4'>{{ question.question_text }}</h1>
    <table class="table">
        {% for choice in question.choice_set.all %}
        <tr>
            <th scope="row"> {{ choice.choice_text }}
            <th scope="row"> {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </th>
        </tr>
        {% endfor %}
    </table>
    <a class="btn btn-success" href="{% url 'polls:detail' question.id %}">Vote again?</a>

    {% endblock content %}